# Generated by Django 5.1.6 on 2025-02-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityimages',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='cityimages',
            name='image',
        ),
        migrations.AddField(
            model_name='cityimages',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityimages',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.city'),
            preserve_default=False,
        ),
    ]
