# Generated by Django 5.1.6 on 2025-02-26 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_cityimages_city_name_remove_cityimages_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityimages',
            name='blog',
        ),
        migrations.AddField(
            model_name='cityimages',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cityimages',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
