# Generated by Django 5.1.6 on 2025-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_cityimages_blog_cityimages_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimages',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='city_images/'),
            preserve_default=False,
        ),
    ]
