# Generated by Django 5.1.6 on 2025-02-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_cityimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityimages',
            name='user',
        ),
        migrations.AddField(
            model_name='cityimages',
            name='blog',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.blog'),
            preserve_default=False,
        ),
    ]
