# Generated by Django 5.1 on 2025-02-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_cityimages_user_cityimages_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityimages',
            name='status',
        ),
    ]
